# Generated by Django 5.0.6 on 2024-07-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('birth_date', models.DateField()),
                ('daily_activity', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('high', 'High')], max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_personal_details',
            },
        ),
        migrations.CreateModel(
            name='ValuesConsumedPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_carbs', models.FloatField()),
                ('total_protein', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('total_cals', models.FloatField()),
                ('total_water', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_nutrition_personal_details', models.ForeignKey(db_column='id_nutrition_personal_details', on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutritionpersonaldetails')),
            ],
            options={
                'db_table': 'values_consumed_per_day',
            },
        ),
    ]
