# Generated by Django 5.0.6 on 2024-07-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_remove_valuesconsumedperday_id_recommended_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuesrecommendedperday',
            name='water',
        ),
        migrations.AddField(
            model_name='valuesrecommendedperday',
            name='water_cups',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='valuesrecommendedperday',
            name='water_liters',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesrecommendedperday',
            name='cals',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesrecommendedperday',
            name='carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesrecommendedperday',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesrecommendedperday',
            name='protein',
            field=models.FloatField(null=True),
        ),
    ]
