# Generated by Django 5.0.6 on 2024-07-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_remove_valuesrecommendedperday_water_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuesconsumedperday',
            name='total_cals',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesconsumedperday',
            name='total_carbs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesconsumedperday',
            name='total_fat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesconsumedperday',
            name='total_protein',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='valuesconsumedperday',
            name='total_water',
            field=models.FloatField(null=True),
        ),
    ]
