# Generated by Django 5.0.6 on 2024-07-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
