# Generated by Django 5.0.6 on 2024-07-21 19:13

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(null=True, storage=authentication.models.MediaStorage(), upload_to='profiles/'),
        ),
    ]
