# Generated by Django 5.0.6 on 2024-07-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesViewSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.TextField()),
                ('type_meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert')], max_length=50)),
                ('cals_kcal', models.FloatField(blank=True, default=0.0)),
                ('protein_g', models.FloatField(blank=True, default=0.0)),
                ('carbs_g', models.FloatField(blank=True, default=0.0)),
                ('fat_g', models.FloatField(blank=True, default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
    ]
